services:
    elendev.widget.widget_repository:
        class: Elendev\WidgetBundle\Widget\WidgetRepository
        
    elendev.widget.twig_extension:
        class: Elendev\WidgetBundle\Twig\Extension\WidgetExtension
        arguments: ["@elendev.widget.widget_repository", '%elendev_widget.hinclude.behavior%']
        tags:
            - { name: twig.extension }